name: "auth-test"

services:
  api:
    image: auth-api
    build: api/.
    container_name: auth-api
    networks:
      - auth-net
    ports:
      - "8080:8080"
    volumes:
      - "./api/src:/auth-api/src"
    depends_on:
      - db

  db:
    image: auth-bd
    build: db/.
    container_name: auth-bd
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - auth-net
    ports:
      - "3306:3306"

networks:
  auth-net:
    name: auth-net
    driver: bridge